/* supervisi-bank.js — bank kalimat untuk supervisi-otomatis.js (hanya data, tidak ada logika).
   Cara menambah variasi: cukup tambahkan kalimat ke larik yang sesuai.

   SUP    = topik pelaksanaan pembelajaran (form Supervisi). Tiap topik:
              k    kunci unik · re  pola pengenal teks butir (huruf kecil) · nama  frasa benda untuk dipakai di kalimat komentar
              s    pengamatan saat nilai 4 (kalimat utuh bersubjek, huruf kecil, tanpa titik)
              p    pengamatan saat nilai 3 (sebagian terpenuhi, memuat temuan spesifik)
              w    pengamatan saat nilai 1–2 (belum / lemah)
              ak   saran tindakan, SELALU diawali kata kerja ber-"me-" (dipasang setelah "Sebaiknya", "Disarankan untuk", dst.)
   TELAAH = topik telaah perangkat (butir pilihan Ada / Sesuai / Perlu perbaikan + kolom Catatan). Tiap topik: ok (nilai 4), kr (nilai ≤3), ak.
   TAMBAH = tambahan p / w / s untuk topik lama (form Perencanaan & Implementasi versi awal) yang bank utamanya ada di supervisi-otomatis.js.
   Token: {mapel} → nama mapel · {kelas} → kelas · {r} → ruang belajar (bengkel / ruang praktik / kelas). */
var SvBank = (function () {
  var SUP = [
    { k: 'x_suasana', re: /suasana siap belajar|salam, doa/, nama: 'penciptaan suasana siap belajar di awal pelajaran',
      s: ['guru menyapa murid di pintu {r}, mengajak berdoa singkat, lalu mengecek kehadiran dan kondisi murid satu per satu',
        'pelajaran dibuka dengan salam dan doa, guru menanyakan kabar murid, dan murid yang belum siap langsung diarahkan',
        'sebelum masuk materi guru memastikan murid duduk rapi dengan perlengkapan di meja, kehadiran dicek dengan cepat',
        'guru mengajak murid menarik napas sejenak dan menyiapkan diri; murid terlihat tenang dan fokus',
        'guru mengingatkan perlengkapan belajar dan aturan keselamatan yang berlaku, murid menjawab serempak lalu bersiap'],
      p: ['salam dan doa berlangsung, tetapi pengecekan kondisi murid hanya sekilas sehingga beberapa murid masih sibuk sendiri',
        'kelas baru benar-benar tenang setelah beberapa menit karena sebagian murid terlambat bersiap',
        'suasana awal cukup kondusif, hanya pengingat keselamatan kerja belum disampaikan dengan jelas',
        'guru membuka dengan salam dan presensi, namun belum menggali kesiapan murid secara emosional'],
      w: ['pembukaan berlangsung singkat dan langsung masuk materi tanpa memastikan kesiapan murid',
        'kelas masih ramai saat pelajaran dimulai dan belum ditertibkan',
        'tidak tampak kegiatan pembuka yang mengondisikan murid untuk belajar'],
      ak: ['menyediakan rutinitas pembuka yang singkat (salam, doa, cek kehadiran dan kesiapan) agar murid cepat siap',
        'menanyakan kondisi murid secara singkat sebelum masuk ke materi',
        'menyampaikan pengingat keselamatan kerja sebelum kegiatan praktik dimulai',
        'menunggu sampai kelas tenang sebelum memulai kegiatan inti'] },

    { k: 'x_apersepsi', re: /apersepsi/, nama: 'apersepsi dan pertanyaan pemantik',
      s: ['guru membuka dengan pertanyaan pemantik tentang pengalaman sehari-hari murid yang berkaitan dengan {mapel}, dan banyak murid mengangkat tangan untuk menjawab',
        'guru menampilkan gambar atau contoh kejadian nyata sebagai pemantik, lalu murid diminta menebak kaitannya dengan materi hari ini',
        'apersepsi dilakukan lewat tanya jawab singkat tentang materi pertemuan lalu, kemudian dihubungkan dengan kegiatan hari ini',
        'guru mengaitkan materi dengan situasi di dunia kerja yang dekat dengan jurusan murid sehingga mereka langsung punya gambaran manfaatnya',
        'guru memulai dengan cerita pendek yang relevan lalu melempar pertanyaan yang memancing murid berpendapat'],
      p: ['apersepsi dilakukan lewat tanya jawab, tetapi pertanyaannya hanya dijawab beberapa murid yang itu-itu saja',
        'pemantik sudah ada, hanya kaitannya dengan pengalaman atau dunia kerja murid belum dijelaskan',
        'apersepsi cenderung berupa pengulangan materi lama dan belum memancing rasa ingin tahu murid',
        'pemantik disampaikan dengan baik, namun waktunya agak lama sehingga kegiatan inti jadi mundur'],
      w: ['guru langsung masuk ke materi tanpa apersepsi atau pemantik',
        'apersepsi tidak tampak; murid belum diajak mengaitkan materi dengan pengalamannya',
        'pertanyaan pemantik terlalu umum dan tidak ditanggapi murid'],
      ak: ['menyiapkan satu pertanyaan pemantik yang dekat dengan pengalaman atau dunia kerja murid',
        'memberi kesempatan kepada lebih banyak murid untuk menjawab pemantik, tidak hanya yang aktif',
        'membatasi waktu apersepsi agar kegiatan inti punya waktu yang cukup',
        'menghubungkan apersepsi dengan tujuan pembelajaran hari itu'] },

    { k: 'x_tp', re: /menyampaikan tp|kriteria keberhasilan secara jelas/, nama: 'penyampaian tujuan dan kriteria keberhasilan',
      s: ['guru menuliskan tujuan pembelajaran di papan dan membacakannya bersama murid, lengkap dengan indikator keberhasilan hari itu',
        'tujuan dan kriteria keberhasilan dijelaskan dengan bahasa yang mudah, lalu beberapa murid diminta menyebutkan kembali apa yang akan dicapai',
        'murid diberi tahu produk atau kemampuan apa yang diharapkan di akhir pelajaran sehingga mereka tahu arah belajarnya',
        'guru menyampaikan tujuan sambil menunjukkan contoh hasil kerja yang diharapkan'],
      p: ['tujuan pembelajaran disampaikan, tetapi kriteria keberhasilannya belum dijabarkan sehingga sebagian murid belum tahu ukuran berhasil',
        'TP dibacakan sekilas tanpa dicek apakah murid memahaminya',
        'kriteria disebutkan secara lisan saja dan tidak ditampilkan, jadi mudah terlupa selama kegiatan'],
      w: ['tujuan pembelajaran tidak disampaikan kepada murid',
        'murid tampak belum tahu apa yang harus dicapai pada pelajaran ini'],
      ak: ['menuliskan TP dan kriteria keberhasilan di papan atau slide agar terlihat sepanjang pelajaran',
        'meminta beberapa murid menyampaikan kembali tujuan dengan bahasa mereka sendiri',
        'menunjukkan contoh hasil kerja yang diharapkan sebagai gambaran kriteria'] },

    { k: 'x_materi', re: /penguasaan materi/, nama: 'penguasaan materi',
      s: ['penjelasan guru akurat dan runtut, istilah teknis dipakai dengan tepat, serta sesuai dengan CP/TP',
        'guru menjawab pertanyaan murid dengan yakin dan memberi contoh yang mutakhir',
        'materi {mapel} disajikan sesuai CP/TP dan guru mampu menghubungkan antarkonsep tanpa terpaku pada catatan',
        'guru menguasai materi dengan baik; contoh yang dipakai terkini dan relevan dengan perkembangan bidangnya'],
      p: ['materi pada umumnya benar, hanya ada beberapa istilah yang kurang tepat dan belum dikoreksi',
        'penjelasan sudah sesuai TP, tetapi contoh yang dipakai belum menggambarkan perkembangan terbaru',
        'guru tampak kurang yakin saat menjawab pertanyaan di luar rencana sehingga jawabannya belum tuntas'],
      w: ['terdapat beberapa kekeliruan konsep dalam penjelasan guru',
        'penjelasan melebar dari CP/TP dan sulit diikuti murid'],
      ak: ['memperbarui contoh dan referensi sesuai perkembangan terkini di bidangnya',
        'mengecek kembali istilah teknis sebelum mengajar',
        'menyiapkan jawaban atas kemungkinan pertanyaan murid di luar rencana'] },

    { k: 'x_model', re: /model\/metode/, nama: 'penerapan model atau metode pembelajaran',
      s: ['model pembelajaran yang dipilih cocok dengan materi, dan langkah-langkahnya (orientasi, kerja kelompok, presentasi) berjalan runtut',
        'sintaks model berjalan berurutan; murid tahu apa yang harus dikerjakan pada setiap tahap',
        'guru memakai demonstrasi lalu praktik terbimbing, dan transisi antartahap berjalan mulus',
        'metode yang dipakai sesuai karakter materi dan guru konsisten mengikuti sintaksnya dari awal sampai akhir'],
      p: ['model yang dipilih sudah tepat, tetapi beberapa tahap sintaks terlewat atau dilakukan terburu-buru',
        'langkah model berjalan, namun peran murid pada tahap tertentu masih belum jelas',
        'metode masih didominasi ceramah sehingga ciri khas model belum tampak penuh'],
      w: ['model atau metode tidak tampak jelas; kegiatan lebih banyak penjelasan satu arah',
        'sintaks model tidak diikuti sehingga alur kegiatan melompat-lompat'],
      ak: ['menjalankan sintaks model secara utuh dengan alokasi waktu yang sudah ditetapkan untuk tiap tahap',
        'memperjelas pembagian peran murid pada setiap tahap',
        'mengurangi ceramah dan menambah aktivitas yang menjadi ciri khas model'] },

    { k: 'x_nalar', re: /penalaran kritis/, nama: 'pengembangan penalaran kritis dan kreativitas',
      s: ['guru mengajukan pertanyaan “mengapa” dan “bagaimana jika”, dan murid menanggapi dengan alasan yang masuk akal',
        'murid diberi masalah terbuka dan boleh menawarkan lebih dari satu cara penyelesaian; beberapa gagasan murid cukup kreatif',
        'guru memancing murid membandingkan dua pendekatan dan menyebutkan alasan pilihannya',
        'pertanyaan guru bertingkat, dari mengingat sampai menganalisis, dan murid terlihat berpikir dulu sebelum menjawab'],
      p: ['pertanyaan guru sebagian besar masih bertipe mengingat sehingga jawaban murid pendek-pendek',
        'ada pertanyaan tingkat tinggi, tetapi guru terlalu cepat memberi jawaban sebelum murid sempat berpikir',
        'masalah yang diberikan hanya memiliki satu jawaban benar sehingga ruang kreativitas murid terbatas'],
      w: ['kegiatan belum menuntut murid berpikir kritis; murid hanya menyalin dan menghafal',
        'tidak tampak pertanyaan atau tugas yang memancing nalar dan kreativitas'],
      ak: ['menyiapkan pertanyaan tingkat tinggi (mengapa, bagaimana jika) dan memberi jeda berpikir sebelum murid menjawab',
        'memberikan masalah terbuka yang boleh diselesaikan dengan beragam cara',
        'meminta murid menjelaskan alasan di balik setiap jawabannya'] },

    { k: 'x_aktif', re: /berpartisipasi aktif/, nama: 'keaktifan murid dan peran guru sebagai fasilitator',
      s: ['murid aktif berdiskusi, bertanya, dan mengerjakan tugas, sementara guru berkeliling sebagai fasilitator',
        'porsi bicara murid lebih banyak daripada guru; guru lebih banyak mengarahkan dan memberi pertanyaan',
        'hampir seluruh murid terlibat dalam kerja kelompok dan guru memantau dari kelompok ke kelompok',
        'guru memberi ruang bagi murid mencoba lebih dulu, lalu membantu bila mereka mengalami kesulitan'],
      p: ['sebagian murid aktif, tetapi beberapa di barisan belakang masih diam dan belum dilibatkan',
        'guru masih sering berdiri di depan dan menjelaskan lama sehingga waktu kerja murid berkurang',
        'keaktifan murid muncul saat kerja kelompok, namun pada sesi tanya jawab hanya segelintir yang bicara'],
      w: ['pembelajaran didominasi ceramah guru; murid hanya mendengarkan dan mencatat',
        'murid pasif dan guru belum berperan sebagai fasilitator'],
      ak: ['membagi peran dalam kelompok agar setiap murid punya tugas',
        'berkeliling dan menyapa murid yang cenderung diam',
        'mengurangi durasi penjelasan di depan dan menambah waktu kerja murid'] },

    { k: 'x_gembira', re: /pembelajaran menggembirakan/, nama: 'suasana belajar yang menggembirakan',
      s: ['suasana kelas hangat; murid sering tersenyum dan tidak takut salah ketika menjawab',
        'guru menyelipkan humor ringan dan apresiasi, dan murid tampak termotivasi serta percaya diri',
        'murid bersemangat mengerjakan tugas dan saling menyemangati; tidak ada yang tampak tertekan',
        'ketika ada murid yang keliru, guru menanggapinya dengan ramah dan teman-temannya ikut membantu'],
      p: ['suasana cukup positif, tetapi beberapa murid terlihat ragu menjawab karena takut salah',
        'semangat murid naik turun; pada bagian tugas individu mereka mulai tampak jenuh',
        'apresiasi guru baru diberikan kepada murid tertentu saja'],
      w: ['suasana kelas tegang dan murid enggan berpendapat',
        'murid tampak kurang termotivasi dan cepat bosan'],
      ak: ['memberi apresiasi yang spesifik kepada lebih banyak murid',
        'menciptakan suasana yang aman untuk salah, misalnya dengan membahas kekeliruan sebagai bahan belajar bersama',
        'menyisipkan aktivitas ringan atau permainan singkat saat murid mulai jenuh'] },

    { k: 'x_diferensiasi', re: /diferensiasi/, nama: 'diferensiasi pembelajaran',
      s: ['guru menyiapkan tugas dengan tingkat kesulitan berbeda, dan murid yang cepat selesai diberi tantangan tambahan',
        'murid yang kesulitan didampingi langsung oleh guru atau teman tutor, sedangkan yang sudah paham mendapat soal pengayaan',
        'tersedia pilihan cara mengerjakan (tulis, praktik, atau presentasi) sehingga murid bisa memilih sesuai kekuatannya',
        'guru memperhatikan murid yang berkebutuhan khusus dan menyesuaikan instruksi serta waktu pengerjaannya'],
      p: ['guru mendampingi murid yang kesulitan, tetapi tugas untuk murid yang sudah paham belum disiapkan sehingga mereka menunggu',
        'diferensiasi baru tampak pada pendampingan, belum pada konten maupun produk',
        'semua murid mendapat tugas yang sama dan bantuan hanya diberikan bila murid meminta'],
      w: ['seluruh murid diperlakukan sama tanpa memperhatikan perbedaan kesiapan',
        'tidak tampak penyesuaian tugas atau dukungan bagi murid yang berbeda kebutuhan'],
      ak: ['menyiapkan tugas bertingkat (dasar, menengah, tantangan) berdasarkan hasil asesmen diagnostik',
        'memanfaatkan tutor sebaya untuk membantu teman yang belum paham',
        'menyediakan pilihan produk atau cara menunjukkan pemahaman'] },

    { k: 'x_kolab', re: /kolaborasi murid|kemitraan dengan dudi/, nama: 'kolaborasi murid dan kemitraan dengan DUDI',
      s: ['murid bekerja dalam tim dengan peran yang jelas (ketua, pencatat, pelaksana) dan koordinasi antaranggota berjalan baik',
        'praktisi atau instruktur dari DUDI dilibatkan untuk memberi masukan pada hasil kerja murid',
        'tim saling membantu dan membagi tugas secara adil; guru memantau kontribusi setiap anggota',
        'guru mengaitkan tugas dengan kebutuhan mitra industri, dan murid berdiskusi memakai standar yang berlaku di industri'],
      p: ['kerja tim berjalan, tetapi pembagian peran belum merata sehingga beberapa murid hanya menonton',
        'kolaborasi antarmurid baik, hanya keterlibatan DUDI atau praktisi belum tampak pada pertemuan ini',
        'peran dalam tim sudah ditetapkan, namun tidak dipantau sehingga dominasi satu dua murid masih terjadi'],
      w: ['murid bekerja sendiri-sendiri dan belum ada kerja sama yang berarti',
        'tidak tampak kemitraan dengan DUDI atau praktisi dalam kegiatan ini'],
      ak: ['menetapkan peran yang jelas dan bergilir dalam setiap tim',
        'melibatkan praktisi atau instruktur DUDI, minimal untuk memberi umpan balik pada produk murid',
        'menilai kontribusi individu di dalam kerja kelompok'] },

    { k: 'x_lingk', re: /lingkungan belajar \(fisik|k3lh/, nama: 'penataan lingkungan belajar serta penerapan K3LH dan 5R',
      s: ['{r} tertata rapi, alat tersimpan pada tempatnya, dan murid memakai APD sesuai jenis pekerjaan',
        'prinsip 5R (ringkas, rapi, resik, rawat, rajin) tampak diterapkan; jalur kerja bersih dan aman',
        'guru mengecek kelengkapan APD dan kondisi alat sebelum praktik, serta menegur murid yang abai dengan sopan',
        'ruang belajar tertata mendukung kerja kelompok, pencahayaan dan ventilasi cukup, dan rambu keselamatan terpasang'],
      p: ['penataan ruang sudah baik, tetapi beberapa murid belum memakai APD secara lengkap dan belum ditegur',
        'K3LH diingatkan di awal, namun saat praktik berlangsung tidak dipantau lagi',
        'alat dan bahan sempat berserakan di meja kerja karena penyimpanan belum teratur'],
      w: ['{r} kurang tertata dan prosedur K3LH belum diterapkan',
        'tidak tampak penerapan 5R maupun pengecekan keselamatan sebelum praktik'],
      ak: ['membuat daftar periksa APD dan alat sebelum praktik dimulai',
        'membiasakan murid merapikan dan membersihkan area kerja di akhir kegiatan (5R)',
        'memantau penerapan K3LH selama praktik, bukan hanya di awal'] },

    { k: 'x_digital', re: /teknologi dimanfaatkan/, nama: 'pemanfaatan teknologi dan AI secara etis',
      s: ['murid memakai internet dan aplikasi untuk mencari sumber, dan guru mengingatkan agar kebenaran sumbernya dicek',
        'guru memanfaatkan simulasi atau video pembelajaran, kemudian murid mencoba sendiri dengan perangkat yang tersedia',
        'AI dipakai sebagai alat bantu bertanya dan guru menegaskan batasannya; hasil kerja tetap dikerjakan murid sendiri',
        'perangkat digital dipakai untuk berkolaborasi (dokumen bersama) dan penggunaannya terarah pada tujuan pembelajaran'],
      p: ['teknologi dipakai guru untuk menyajikan materi, tetapi murid belum diberi kesempatan memakainya untuk belajar',
        'pemanfaatan digital sudah ada, namun aspek etika dan keaslian karya belum disinggung',
        'koneksi atau perangkat sempat bermasalah dan belum ada rencana cadangan sehingga kegiatan tersendat beberapa menit'],
      w: ['teknologi tidak dimanfaatkan padahal sarananya tersedia',
        'penggunaan perangkat oleh murid tidak terarah dan sebagian membuka hal di luar pelajaran'],
      ak: ['memberi tugas yang menuntut murid memakai teknologi untuk mencari, mengolah, atau membuat sesuatu',
        'menjelaskan etika memakai AI dan pentingnya menyebut sumber',
        'menyiapkan cadangan materi tanpa jaringan bila perangkat bermasalah'] },

    { k: 'x_produk', re: /produk\/jasa\/proyek/, nama: 'kaitan produk atau proyek murid dengan standar kerja',
      s: ['tugas proyek mengarah pada produk nyata dan dinilai dengan standar kompetensi kerja (SKKNI) yang relevan',
        'murid mengerjakan pekerjaan yang menyerupai kondisi kerja sebenarnya, dengan kriteria mutu yang jelas',
        'produk murid dicek terhadap standar industri dan guru menunjukkan contoh pekerjaan yang diterima di dunia kerja',
        'proyek yang dikerjakan menjawab kebutuhan nyata (pelanggan atau unit produksi sekolah) sehingga murid terlihat bersungguh-sungguh'],
      p: ['tugas sudah mengarah ke produk, tetapi acuan standar kerjanya belum disebutkan',
        'produk dinilai dari kerapian saja, belum mengacu pada standar kompetensi yang jelas',
        'konteks kebutuhan nyata baru disinggung sekilas dan belum menjadi dasar pengerjaan'],
      w: ['tugas masih bersifat latihan soal dan belum mengarah pada produk atau jasa nyata',
        'tidak ada kaitan dengan standar kompetensi kerja dalam penugasan'],
      ak: ['menautkan tugas dengan unit kompetensi dalam SKKNI atau standar industri yang relevan',
        'melibatkan kebutuhan nyata (TEFA atau pesanan) sebagai konteks proyek',
        'menyiapkan lembar kriteria mutu produk yang dipahami murid'] },

    { k: 'x_formatif', re: /asesmen formatif berlangsung/, nama: 'asesmen formatif selama pembelajaran',
      s: ['guru memantau pemahaman lewat tanya jawab, pengamatan unjuk kerja, dan exit ticket di akhir kegiatan',
        'selama praktik guru memakai checklist unjuk kerja untuk setiap murid sehingga perkembangan mereka tercatat',
        'guru mengecek pemahaman di tengah pelajaran dengan kuis singkat, lalu menyesuaikan penjelasan berdasarkan jawaban murid',
        'beragam teknik asesmen formatif dipakai (pertanyaan lisan, pengamatan, tugas singkat) dan hasilnya dicatat'],
      p: ['asesmen formatif dilakukan lewat tanya jawab, tetapi hasilnya tidak dicatat dan belum dipakai untuk menyesuaikan pembelajaran',
        'pengecekan pemahaman baru dilakukan di akhir sehingga kesalahan konsep terlambat diketahui',
        'teknik asesmen cenderung satu jenis (tanya jawab lisan) dan menjangkau sedikit murid'],
      w: ['tidak tampak asesmen formatif selama pembelajaran',
        'guru belum memantau pemahaman murid secara sistematis'],
      ak: ['menyiapkan checklist atau exit ticket untuk mencatat capaian murid',
        'mengecek pemahaman di tengah pelajaran agar penjelasan bisa langsung diperbaiki',
        'memvariasikan teknik asesmen formatif'] },

    { k: 'x_umpan', re: /umpan balik spesifik/, nama: 'umpan balik kepada murid',
      s: ['guru memberi umpan balik yang spesifik (“bagian ini sudah tepat, tinggal rapikan langkah ketiga”) dan murid langsung memperbaiki pekerjaannya',
        'umpan balik diberikan saat itu juga, dan murid diberi kesempatan mengulang atau merevisi hasil kerjanya',
        'guru menyebutkan kekuatan dan bagian yang perlu diperbaiki dari pekerjaan murid, bukan sekadar menyatakan benar atau salah',
        'murid saling memberi masukan terhadap pekerjaan temannya dengan panduan dari guru'],
      p: ['umpan balik diberikan, tetapi masih umum (“bagus”, “kurang rapi”) sehingga murid belum tahu bagian mana yang harus diperbaiki',
        'umpan balik baru menjangkau sebagian murid; murid lain belum sempat didatangi',
        'murid menerima masukan namun belum diberi kesempatan memperbaiki pada pelajaran yang sama'],
      w: ['hampir tidak ada umpan balik atas pekerjaan murid',
        'guru hanya menyatakan benar atau salah tanpa penjelasan'],
      ak: ['memberi umpan balik yang menyebut bagian yang sudah tepat dan bagian yang perlu diperbaiki',
        'menyediakan waktu bagi murid untuk memperbaiki pekerjaan setelah menerima masukan',
        'menjangkau semua kelompok dengan jadwal berkeliling yang terencana'] },

    { k: 'x_rubrik', re: /kriteria\/rubrik penilaian/, nama: 'penggunaan kriteria atau rubrik penilaian',
      s: ['rubrik ditampilkan dan dijelaskan di awal; murid mengecek pekerjaannya dengan rubrik itu sebelum dikumpulkan',
        'kriteria penilaian selaras dengan TP dan dipakai guru ketika memberi komentar atas hasil kerja',
        'murid tahu seperti apa pekerjaan yang baik karena rubrik dan contoh hasil sudah dibagikan'],
      p: ['rubrik tersedia, tetapi tidak dibahas bersama murid sehingga fungsinya belum optimal',
        'kriteria sudah mengikuti TP, namun deskriptor tiap level belum jelas',
        'murid mengetahui kriteria secara garis besar, tetapi tidak ada rujukan tertulis di kelas'],
      w: ['tidak ada kriteria atau rubrik yang disampaikan kepada murid',
        'penilaian dilakukan tanpa acuan kriteria yang dikenal murid'],
      ak: ['membahas rubrik bersama murid sebelum mereka mengerjakan tugas',
        'melengkapi rubrik dengan deskriptor yang jelas pada setiap level',
        'meminta murid melakukan penilaian diri dengan rubrik tersebut'] },

    { k: 'x_kelola', re: /pengelolaan waktu/, nama: 'pengelolaan waktu, transisi, dan perilaku murid',
      s: ['alokasi waktu tiap tahap sesuai rencana dan transisi berlangsung cepat dengan instruksi yang jelas',
        'guru mengelola perilaku murid secara positif: menegur dengan tenang dan memberi penguatan pada perilaku yang diharapkan',
        'waktu terpakai efektif; tidak ada jeda kosong yang berarti dan pelajaran selesai tepat waktu',
        'tata tertib kelas disepakati dan ditegakkan secara konsisten tanpa membuat murid merasa dimarahi'],
      p: ['waktu inti sedikit terpotong karena pembukaan yang panjang sehingga penutup agak terburu-buru',
        'transisi antarkegiatan masih memakan beberapa menit karena instruksi harus diulang-ulang',
        'teguran kepada murid yang gaduh sudah ada, tetapi belum konsisten'],
      w: ['waktu tidak terkelola dengan baik; beberapa tahap tidak terlaksana',
        'kelas sulit dikendalikan dan perilaku murid belum tertangani'],
      ak: ['membuat pembagian waktu per tahap dan memakai penanda waktu (timer)',
        'memberikan instruksi transisi secara singkat dan jelas, disertai contoh',
        'menetapkan kesepakatan kelas dan menegakkannya secara konsisten dan positif'] },

    { k: 'x_interaksi', re: /interaksi guru-murid/, nama: 'interaksi guru dan murid',
      s: ['guru menyapa murid dengan nama, bahasanya santun, dan memperlakukan semua murid secara adil',
        'interaksi hangat; guru mendengarkan pendapat murid sampai selesai dan menanggapinya dengan menghargai',
        'guru menyebut nama murid ketika memberi pertanyaan dan tidak membeda-bedakan, termasuk kepada murid yang kurang aktif',
        'guru memakai bahasa yang komunikatif dan murid merasa bebas bertanya'],
      p: ['interaksi dengan murid yang aktif sangat baik, tetapi dengan murid yang pendiam masih minim',
        'bahasa guru santun; hanya nada instruksinya kadang terlalu cepat sehingga ada murid yang ragu bertanya',
        'sapaan hangat tampak di awal, tetapi berkurang ketika waktu mulai mepet'],
      w: ['interaksi berlangsung satu arah dan kurang hangat',
        'ada murid yang diabaikan atau ditanggapi kurang santun'],
      ak: ['menyapa dan menyebut nama murid yang pendiam agar mereka merasa dilihat',
        'memberi kesempatan murid menyelesaikan pendapatnya sebelum menanggapi',
        'memastikan semua murid mendapat giliran berbicara'] },

    { k: 'x_dpl', re: /dimensi profil lulusan yang direncanakan tampak/, nama: 'penguatan dimensi profil lulusan',
      s: ['dimensi kemandirian dan kolaborasi tampak jelas: murid mengerjakan tugas sendiri lalu berdiskusi dengan timnya',
        'guru menekankan penalaran kritis dan komunikasi, dan murid mempresentasikan hasil kerjanya dengan runtut',
        'nilai profil lulusan yang direncanakan (misalnya kemandirian dan kolaborasi) benar-benar muncul pada perilaku murid selama kegiatan',
        'guru menyebut dimensi profil lulusan yang disasar hari ini dan memberi penguatan ketika murid menunjukkannya'],
      p: ['dimensi profil lulusan yang direncanakan muncul sebagian, misalnya kolaborasi, tetapi komunikasi belum tampak',
        'guru belum menyebutkan dimensi yang disasar sehingga murid belum menyadarinya',
        'dimensi profil lulusan baru tampak pada beberapa murid'],
      w: ['dimensi profil lulusan yang direncanakan belum tampak dalam kegiatan',
        'kegiatan belum memberi ruang bagi munculnya karakter yang direncanakan'],
      ak: ['menyebutkan dimensi profil lulusan yang disasar dan memberi penguatan ketika murid memunculkannya',
        'merancang aktivitas yang memberi kesempatan murid berlatih dimensi tersebut',
        'menyiapkan indikator perilaku yang diamati untuk setiap dimensi'] },

    { k: 'x_simpul', re: /menyimpulkan bersama/, nama: 'penutupan dan refleksi pembelajaran',
      s: ['guru memandu murid menyimpulkan materi dengan pertanyaan “apa yang kita pelajari, mengapa penting, dan bagaimana dipakai di dunia kerja”',
        'di akhir pelajaran beberapa murid menyampaikan simpulan dan kesulitan yang dialami, lalu guru meluruskan bila perlu',
        'refleksi dilakukan lewat lembar singkat: murid menuliskan satu hal yang dipelajari dan satu hal yang masih membingungkan',
        'penutupan berlangsung tepat waktu dengan simpulan bersama dan penguatan dari guru'],
      p: ['guru menyimpulkan sendiri di akhir, sedangkan murid belum diajak merumuskan simpulan',
        'refleksi berupa pertanyaan umum (“sudah paham?”) dan belum menggali pengalaman belajar murid',
        'penutupan agak terburu-buru karena waktu habis sehingga refleksi dipersingkat'],
      w: ['pelajaran berakhir tanpa simpulan maupun refleksi',
        'tidak ada kegiatan penutup yang berarti'],
      ak: ['menyisakan 5–10 menit terakhir untuk simpulan dan refleksi bersama murid',
        'memakai pertanyaan refleksi yang menghubungkan materi dengan penerapannya di dunia kerja',
        'meminta murid menuliskan satu hal yang dipelajari dan satu hal yang masih membingungkan'] },

    { k: 'x_lanjut', re: /memberi tindak lanjut \(pengayaan/, nama: 'tindak lanjut dan penutupan praktik',
      s: ['guru memberi tugas pengayaan bagi yang sudah tuntas dan remedial bagi yang belum, serta menyampaikan materi pertemuan berikutnya',
        'murid diminta merapikan alat dan membersihkan area kerja sebelum keluar, lalu guru menginformasikan tugas berikutnya',
        'informasi pembelajaran berikutnya disampaikan jelas, termasuk apa yang perlu dipersiapkan murid',
        'tindak lanjut disesuaikan dengan hasil hari ini: ada tugas lanjutan, pengayaan, atau remedial'],
      p: ['tugas lanjutan diberikan, tetapi pengayaan atau remedial belum dibedakan sesuai capaian murid',
        'alat dirapikan oleh sebagian murid saja dan belum dicek guru',
        'informasi pertemuan berikutnya disampaikan sambil murid berkemas sehingga kurang terdengar'],
      w: ['tidak ada tindak lanjut maupun informasi pertemuan berikutnya',
        'alat dan area kerja ditinggalkan tanpa dirapikan'],
      ak: ['menyiapkan skema pengayaan dan remedial berdasarkan hasil asesmen hari itu',
        'mengecek kerapian alat dan area kerja sebelum murid meninggalkan kelas',
        'menyampaikan informasi pertemuan berikutnya sebelum murid berkemas'] }
  ];

  var TELAAH = [
    { k: 't_cp', re: /capaian pembelajaran \(cp\)/, nama: 'Capaian Pembelajaran (CP)',
      ok: ['CP sudah mengacu pada Kepka BSKAP 046/2025 dan sesuai dengan fase serta elemen mata pelajaran', 'rujukan CP tepat dan dituliskan lengkap sesuai fase murid', 'CP dirujuk dengan benar, termasuk elemen kejuruannya'],
      kr: ['rujukan CP belum menyebut Kepka BSKAP 046/2025 secara tepat', 'CP yang dituliskan belum sesuai dengan fase murid', 'elemen CP belum dirinci sampai bagian yang akan diajarkan'],
      ak: ['menyesuaikan rujukan CP dengan Kepka BSKAP 046/2025 dan fase murid', 'mencantumkan elemen CP yang menjadi fokus pertemuan', 'memeriksa kembali kesesuaian CP dengan mata pelajaran'] },
    { k: 't_tp', re: /tujuan pembelajaran \(tp\) dan alur/, nama: 'rumusan TP dan alur TP',
      ok: ['TP jelas, terukur, dan tersusun berurutan dalam alur yang logis', 'rumusan TP sudah memuat kompetensi dan lingkup materi dengan baik', 'alur TP runtut dan mudah diikuti'],
      kr: ['rumusan TP belum terukur karena kata kerjanya masih umum', 'urutan TP pada alur belum sepenuhnya logis', 'lingkup materi dalam TP belum disebutkan'],
      ak: ['memakai kata kerja operasional yang terukur pada setiap TP', 'menata ulang alur TP dari yang mendasar ke yang kompleks', 'menambahkan lingkup materi pada rumusan TP'] },
    { k: 't_modul', re: /rencana pembelajaran\/modul ajar/, nama: 'kelengkapan modul ajar',
      ok: ['modul ajar sudah memuat identifikasi murid, dimensi profil lulusan, dan desain pembelajaran secara lengkap', 'komponen modul lengkap dan saling berkaitan', 'modul ajar tersusun rapi sehingga mudah dipakai'],
      kr: ['identifikasi murid dalam modul masih terlalu singkat', 'dimensi profil lulusan belum dikaitkan dengan desain pembelajaran', 'beberapa komponen modul belum terisi'],
      ak: ['melengkapi identifikasi murid berdasarkan hasil diagnostik', 'mengaitkan dimensi profil lulusan dengan langkah pembelajaran', 'mengecek kelengkapan seluruh komponen modul'] },
    { k: 't_kerangka', re: /kerangka pembelajaran: praktik/, nama: 'kerangka pembelajaran',
      ok: ['praktik pedagogis, kemitraan, lingkungan belajar, dan pemanfaatan digital sudah direncanakan dan terhubung dengan langkah pembelajaran', 'kerangka pembelajaran lengkap dan sesuai karakter materi', 'pemilihan model (misalnya PjBL atau TEFA) tepat untuk materi dan didukung rancangan lingkungan serta digital'],
      kr: ['kemitraan belum dituliskan secara konkret', 'pemanfaatan digital masih sebatas penyajian materi', 'kaitan model pembelajaran dengan langkah kegiatan belum terlihat'],
      ak: ['menuliskan bentuk kemitraan yang konkret (siapa dan berperan apa)', 'menambahkan peran teknologi bagi murid pada langkah kegiatan', 'menjabarkan sintaks model ke dalam langkah kegiatan'] },
    { k: 't_prinsip', re: /prinsip berkesadaran/, nama: 'prinsip berkesadaran, bermakna, dan menggembirakan',
      ok: ['ketiga prinsip tercermin pada rancangan kegiatan', 'rancangan kegiatan terasa bermakna dan menggembirakan bagi murid', 'prinsip pembelajaran mendalam tampak pada hampir semua kegiatan'],
      kr: ['unsur menggembirakan belum tampak pada kegiatan inti', 'kebermaknaan kegiatan bagi murid belum dijelaskan dalam rancangan', 'prinsip berkesadaran belum muncul secara eksplisit'],
      ak: ['menambahkan kegiatan yang menumbuhkan rasa senang dan percaya diri', 'menuliskan manfaat kegiatan bagi murid pada langkah pembelajaran', 'mencantumkan ajakan refleksi agar murid sadar akan proses belajarnya'] },
    { k: 't_jenjang', re: /dirancang berjenjang/, nama: 'pengalaman belajar memahami, mengaplikasi, dan merefleksi',
      ok: ['ketiga pengalaman belajar dirancang berjenjang dari memahami sampai merefleksi', 'urutan memahami, mengaplikasi, merefleksi terlihat jelas', 'jenjang pengalaman belajar logis dan memberi ruang berlatih'],
      kr: ['pengalaman merefleksi belum dirancang sebagai kegiatan tersendiri', 'tahap mengaplikasi belum kontekstual', 'ketiga pengalaman belajar belum terlihat berjenjang'],
      ak: ['menambahkan kegiatan refleksi yang terstruktur di akhir', 'menyusun tugas penerapan yang lebih kontekstual', 'memetakan ketiga pengalaman belajar pada setiap tahap'] },
    { k: 't_dudi', re: /kontekstualisasi dengan dunia kerja/, nama: 'kontekstualisasi dengan dunia kerja',
      ok: ['materi dikaitkan dengan dunia kerja, SKKNI, K3LH, atau produk/jasa TEFA', 'konteks dunia kerja jelas dan relevan dengan kompetensi keahlian', 'keterkaitan dengan DUDI tergambar baik'],
      kr: ['kaitan dengan dunia kerja baru disebut secara umum', 'acuan SKKNI belum dicantumkan', 'aspek K3LH belum dimasukkan dalam rancangan praktik'],
      ak: ['mencantumkan unit kompetensi SKKNI yang relevan', 'menambahkan contoh kasus nyata dari industri', 'memasukkan prosedur K3LH pada langkah praktik'] },
    { k: 't_dpl', re: /dimensi profil lulusan \(keimanan/, nama: 'pemilihan dimensi profil lulusan',
      ok: ['dimensi profil lulusan dipilih relevan dengan materi dan tampak pada kegiatan', 'pilihan dimensi tepat dan konsisten dengan tujuan', 'dimensi yang dituju jelas dan tidak berlebihan'],
      kr: ['dimensi yang dipilih terlalu banyak sehingga kurang fokus', 'dimensi belum dikaitkan dengan kegiatan murid', 'indikator dimensi belum dituliskan'],
      ak: ['memilih dua atau tiga dimensi yang paling relevan', 'menghubungkan dimensi dengan aktivitas murid', 'menuliskan indikator perilaku untuk tiap dimensi'] },
    { k: 't_diag', re: /asesmen diagnostik/, nama: 'asesmen diagnostik',
      ok: ['asesmen diagnostik kognitif dan nonkognitif sudah direncanakan beserta tindak lanjutnya', 'instrumen diagnostik jelas dan hasilnya dipakai menyesuaikan pembelajaran', 'diagnostik tersedia dan relevan dengan kebutuhan murid'],
      kr: ['asesmen diagnostik baru mencakup aspek kognitif', 'tindak lanjut hasil diagnostik belum dijelaskan', 'instrumen diagnostik belum dilampirkan'],
      ak: ['menambahkan diagnostik nonkognitif (minat, gaya belajar, kesiapan)', 'menuliskan tindak lanjut untuk tiap kelompok hasil diagnostik', 'melampirkan instrumen diagnostik'] },
    { k: 't_sumatif', re: /asesmen formatif dan sumatif/, nama: 'asesmen formatif dan sumatif',
      ok: ['asesmen formatif dan sumatif selaras dengan TP dan dilengkapi instrumen atau rubrik', 'rubrik unjuk kerja atau portofolio sudah tersedia', 'bentuk asesmen sesuai karakter kompetensi'],
      kr: ['rubrik belum dilampirkan', 'asesmen sumatif belum sepenuhnya selaras dengan TP', 'asesmen formatif belum dijadwalkan dalam langkah pembelajaran'],
      ak: ['melengkapi rubrik unjuk kerja atau produk', 'memeriksa keselarasan setiap TP dengan bentuk asesmennya', 'menjadwalkan asesmen formatif pada langkah pembelajaran'] },
    { k: 't_diferensiasi', re: /diferensiasi dan inklusivitas/, nama: 'diferensiasi dan inklusivitas',
      ok: ['diferensiasi konten, proses, dan produk sudah direncanakan, termasuk bagi murid berkebutuhan khusus', 'rancangan diferensiasi nyata dan bisa dilaksanakan', 'perhatian pada inklusivitas tampak jelas'],
      kr: ['diferensiasi baru pada proses, belum pada konten dan produk', 'dukungan bagi murid berkebutuhan khusus belum dituliskan', 'rancangan diferensiasi masih umum'],
      ak: ['menambahkan pilihan konten atau produk sesuai kesiapan murid', 'mencantumkan penyesuaian bagi murid berkebutuhan khusus', 'menjabarkan diferensiasi dalam langkah pembelajaran'] },
    { k: 't_media', re: /media, alat, bahan/, nama: 'media, alat, bahan, dan keselamatan kerja',
      ok: ['media, alat, dan bahan lengkap dan layak, serta keselamatan kerja diperhatikan', 'ketersediaan bengkel atau lab sudah dicek', 'daftar alat dan bahan jelas'],
      kr: ['daftar alat dan bahan belum dirinci jumlahnya', 'prosedur keselamatan kerja belum dituliskan', 'kelayakan alat belum dicek'],
      ak: ['merinci kebutuhan alat dan bahan beserta jumlahnya', 'menambahkan prosedur keselamatan kerja', 'mengecek alat sebelum pembelajaran dimulai'] },
    { k: 't_tek', re: /pemanfaatan teknologi \(termasuk ai/, nama: 'pemanfaatan teknologi dan integritas akademik',
      ok: ['pemanfaatan teknologi, termasuk AI secara etis, sudah direncanakan dan disertai aturan integritas akademik', 'kebijakan integritas akademik disampaikan dengan jelas', 'teknologi dipilih sesuai kebutuhan materi'],
      kr: ['penggunaan AI belum diatur secara tegas', 'aturan integritas akademik belum dituliskan', 'peran teknologi bagi murid belum jelas'],
      ak: ['menuliskan aturan penggunaan AI dan integritas akademik', 'menjelaskan fungsi teknologi pada setiap langkah', 'mencantumkan cara murid menyebutkan sumber'] }
  ];

  // Tambahan untuk topik lama (kunci sama dengan ASPEK di supervisi-otomatis.js)
  var TAMBAH = {
    tahap: { p: ['kegiatan awal dan inti berjalan sesuai rencana, tetapi penutupan dipersingkat karena waktu habis', 'urutan kegiatan mengikuti perencanaan, hanya pembagian waktunya agak meleset sehingga bagian akhir terburu-buru'], w: ['sebagian besar urutan kegiatan tidak sesuai dengan perencanaan'] },
    dpl: { p: ['tujuan pembelajaran sudah disampaikan, tetapi kaitannya dengan dimensi profil lulusan belum disinggung', 'sebagian kegiatan mengarah ke dimensi profil lulusan, sebagian lain belum terlihat'], w: ['dimensi profil lulusan belum tampak dalam kegiatan'] },
    kriteria: { p: ['kriteria disebutkan sekilas tetapi belum dijelaskan kepada murid', 'penilaian sudah memakai acuan, namun murid belum mengetahui kriterianya'], w: ['penilaian dilakukan tanpa kriteria yang jelas'] },
    asesmen_awal: { p: ['asesmen awal dilakukan lewat tanya jawab, tetapi hasilnya belum dipakai menyesuaikan kegiatan', 'guru menanyakan pengetahuan awal, sedangkan kesiapan emosional murid belum digali'], w: ['asesmen awal tidak dilakukan'] },
    asesmen_proses: { p: ['umpan balik diberikan kepada sebagian murid saja', 'pemantauan selama proses ada, tetapi belum dicatat'], w: ['tidak tampak pemantauan maupun umpan balik selama proses'] },
    asesmen_hasil: { p: ['asesmen akhir dilakukan, tetapi bentuknya tunggal', 'ketercapaian tujuan dicek sekilas dan belum menyeluruh'], w: ['tidak ada asesmen hasil di akhir pelajaran'] },
    selaras: { p: ['sebagian besar kegiatan sejalan dengan tujuan, tetapi ada langkah yang melenceng dari rencana', 'penilaian belum sepenuhnya mengukur tujuan yang disampaikan'], w: ['kegiatan dan penilaian tidak sejalan dengan tujuan'] },
    pedagogis: { p: ['praktik yang dituliskan muncul sebagian, sedangkan peran murid masih terbatas', 'pendekatan sudah dijalankan, tetapi belum utuh'], w: ['praktik pedagogis dalam perencanaan belum tampak'] },
    lingkungan: { p: ['suasana kelas cukup baik, tetapi penataan ruang belum mendukung kerja kelompok', 'lingkungan belajar mendukung, hanya pemanfaatan sumber belajar di sekitar belum maksimal'], w: ['lingkungan belajar belum mendukung kegiatan'] },
    kemitraan: { p: ['kerja sama antarmurid ada, tetapi pihak lain belum dilibatkan sesuai rencana', 'kemitraan yang direncanakan baru terlaksana sebagian'], w: ['kemitraan yang direncanakan tidak terlaksana'] },
    digital: { p: ['media digital dipakai guru, tetapi murid belum menggunakannya', 'perangkat dipakai namun sempat terkendala teknis'], w: ['teknologi digital yang direncanakan tidak dipakai'] },
    memuliakan: { p: ['sikap saling menghargai tampak, tetapi apresiasi belum merata kepada semua murid', 'bahasa santun, namun ada murid yang kurang didengar'], w: ['sikap saling memuliakan belum tampak'] },
    memahami: { s: ['murid membangun konsep lewat kegiatan mengamati, menanya, dan mendiskusikan temuan, bukan hanya mendengarkan'], p: ['murid menggali konsep, tetapi masih banyak mengikuti penjelasan guru', 'sumber belajar yang dipakai terbatas pada satu bahan'], w: ['murid hanya menerima penjelasan tanpa menggali konsep'] },
    mengaplikasi: { s: ['murid menerapkan konsep pada tugas kontekstual dan menjelaskan alasan langkah yang mereka ambil'], p: ['murid menerapkan konsep, tetapi konteksnya belum dekat dengan kehidupan mereka', 'waktu praktik terbatas sehingga tidak semua murid sempat mencoba'], w: ['tidak ada kesempatan bagi murid menerapkan pemahamannya'] },
    merefleksi: { s: ['murid mengevaluasi proses dan strategi belajarnya, lalu menyebutkan hal yang akan diperbaiki pada pertemuan berikutnya'], p: ['refleksi hanya berupa pertanyaan umum di akhir', 'murid belum diarahkan menentukan tindak lanjut belajarnya'], w: ['refleksi tidak dilakukan'] },
    prinsip: { p: ['murid antusias, tetapi tujuan dan manfaat kegiatan belum disadari penuh', 'unsur menggembirakan belum muncul di semua tahap'], w: ['prinsip berkesadaran, bermakna, dan menggembirakan belum tampak'] },
    karakteristik: { p: ['guru menyesuaikan bantuan, tetapi belum bagi semua kelompok', 'variasi kegiatan untuk gaya belajar yang berbeda masih terbatas'], w: ['kegiatan seragam tanpa memperhatikan karakteristik murid'] }
  };

  /* ====================== POLA KALIMAT UMUM ====================== */
  var P = {
    // pembuka pengamatan (diakhiri koma atau "bahwa"; kalimat setelahnya diawali huruf kecil)
    OPEN_OBS: ['Selama pembelajaran,', 'Pada saat observasi,', 'Dari yang saya amati,', 'Di kelas tampak bahwa', 'Saat kegiatan berlangsung,', 'Berdasarkan pengamatan,', 'Terlihat bahwa', 'Sepanjang pelajaran,', 'Pada pertemuan ini,', 'Saya mencatat bahwa', 'Dalam pengamatan kali ini,', 'Yang tampak di kelas,'],
    DAMPAK4: [', sehingga suasana kelas tetap kondusif', ', sehingga kegiatan berjalan lancar', ', sehingga tidak banyak waktu terbuang', ', sehingga kegiatan terasa mengalir', '. Hal itu terlihat dari keterlibatan murid', '. Murid merespons dengan antusias', '. Murid mengikutinya dengan tertib', '. Hasilnya tampak pada pekerjaan murid', '. Murid tampak nyaman menjalaninya', '. Sebagian besar murid mengikutinya dengan baik'],
    SAMBUNG_PLUS: [', lalu ', '; selain itu, ', '. Selain itu, ', '. Pada saat yang sama, ', '. Di samping itu, '],
    KONTRAS: [', namun ', ', hanya saja ', ', tetapi ', '; meski begitu, ', '. Meski demikian, ', '. Akan tetapi, '],
    POS_RINGAN3: ['Meski begitu, suasana kelas tetap kondusif.', 'Walau demikian, murid tetap mengikuti dengan baik.', 'Secara umum kegiatan masih berjalan lancar.', 'Hal ini tidak sampai mengganggu jalannya pembelajaran.', 'Sebagian besar murid tetap menunjukkan usaha yang baik.'],
    // komentar singkat untuk kolom Catatan (nilai 4)
    SING4: ['Sudah baik, pertahankan.', 'Baik.', 'Pertahankan.', 'Sudah sesuai.', 'Tidak ada catatan khusus.', 'Bagus, lanjutkan.', 'Sudah sangat baik.', 'Konsisten, pertahankan.', 'Mantap.'],
    OK_I: ['{n} sudah berjalan dengan baik', '{n} terlaksana sesuai rencana', '{n} sudah tampak nyata dalam praktik di kelas', '{n} dilaksanakan dengan baik dan konsisten', '{n} berlangsung lancar', 'bagian {n} sudah bagus', 'untuk {n}, sudah sangat memadai', '{n} menjadi salah satu kekuatan pada pembelajaran ini', '{n} sudah sesuai harapan', 'saya apresiasi {n} yang sudah tertata dengan baik', '{n} dijalankan dengan percaya diri', 'secara keseluruhan {n} sudah baik'],
    OK_EKOR: [', pertahankan', ', teruskan', ' dan layak dijadikan contoh', ', terima kasih', ', semoga konsisten pada pertemuan berikutnya'],
    KURANG_I: ['{n} sudah berjalan, tetapi masih bisa dimaksimalkan', '{n} perlu diperkuat saat pelaksanaan', '{n} belum merata pada seluruh kegiatan', '{n} sudah cukup, tinggal ditingkatkan', 'pada {n} masih ada ruang untuk berkembang', '{n} sudah mulai tampak, namun belum konsisten', 'untuk {n}, hasilnya sudah lumayan tetapi belum optimal', '{n} perlu mendapat perhatian lebih'],
    KURANG2_I: ['{n} masih lemah dan perlu pembenahan', '{n} baru muncul sebagian kecil', 'sebagian besar unsur {n} belum terlaksana', '{n} perlu dibenahi secara serius', '{n} masih jauh dari harapan'],
    BELUM_I: ['{n} belum tampak sama sekali', 'belum ada upaya yang terlihat pada {n}', '{n} belum dilaksanakan'],
    FRAME: ['Sebaiknya ', 'Disarankan untuk ', 'Ke depan, perlu ', 'Mohon ', 'Coba ', 'Akan lebih baik bila {sapa} ', 'Perlu ', 'Saran saya, '],
    KECIL_SUP: ['pengelolaan waktu agar penutupan dan refleksi tidak terburu-buru', 'pemberian umpan balik yang lebih merata kepada seluruh murid', 'keterlibatan murid yang masih diam agar lebih merata', 'dokumentasi hasil asesmen formatif untuk bahan tindak lanjut', 'variasi pertanyaan pemantik agar lebih menantang', 'pemanfaatan waktu transisi antarkegiatan']
  };

  /* ====================== PENULISAN DARI SUDUT PANDANG GURU ====================== */
  // Jawaban wawancara & refleksi yang ditulis guru (orang pertama). Token {mapel}.
  var GURU = {
    tujuan: ['Tujuan hari ini agar murid mampu menjelaskan dan mempraktikkan materi {mapel} yang dipelajari, bukan sekadar hafal. Saya mengajak mereka mengaitkannya dengan contoh nyata lalu menerapkannya pada tugas.',
      'Saya ingin murid benar-benar paham konsep {mapel} hari ini dan bisa menjelaskan alasan di balik langkah yang mereka ambil. Karena itu kegiatannya saya susun dari memahami, mencoba, lalu merefleksikan.',
      'Targetnya murid dapat memakai materi {mapel} untuk menyelesaikan masalah yang dekat dengan kehidupan atau pekerjaan mereka. Pemahaman mendalam saya lihat dari kemampuan mereka menjelaskan kembali dengan kata-kata sendiri.',
      'Tujuan pembelajaran hari ini sudah saya tuliskan dan akan saya sampaikan di awal. Agar tidak sekadar hafal, murid saya minta bekerja pada kasus nyata dan menjelaskan hasilnya.',
      'Murid diharapkan mampu menerapkan konsep {mapel} secara mandiri dan bekerja sama. Saya memastikan mereka paham lewat pertanyaan pemantik dan tugas yang meminta alasan, bukan hanya jawaban.'],
    kondisi: ['Hasil diagnostik menunjukkan kemampuan murid cukup beragam: sebagian sudah menguasai konsep dasar, sebagian masih perlu penguatan. Karena itu saya membentuk kelompok campuran dan menyiapkan tugas bertingkat.',
      'Sebelum menyusun modul saya mengecek kesiapan murid lewat pertanyaan singkat dan pengamatan. Dari situ saya tahu beberapa murid perlu pendampingan, sehingga saya menyiapkan contoh yang lebih sederhana dan tantangan tambahan untuk yang sudah paham.',
      'Kelas ini cukup beragam gaya belajarnya; ada yang cepat lewat praktik, ada yang perlu penjelasan visual. Maka rancangannya memuat demonstrasi, kerja kelompok, dan tugas mandiri.',
      'Kondisi awal murid saya petakan dari nilai sebelumnya dan wawancara singkat. Hasilnya memengaruhi pembagian kelompok, tingkat kesulitan tugas, dan cara saya memberi umpan balik.',
      'Berdasarkan diagnostik, minat murid lebih tinggi pada kegiatan praktik, sehingga rancangan saya banyak memberi ruang mencoba langsung dan sedikit ceramah.'],
    bermakna: ['Saya mengaitkan topik dengan kasus yang benar-benar dijumpai di dunia kerja, sehingga murid melihat manfaatnya. Mereka juga mengerjakan tugas yang hasilnya bisa dipakai atau ditunjukkan.',
      'Murid diajak menyelesaikan masalah nyata yang berkaitan dengan {mapel}, misalnya kasus dari bengkel atau usaha di sekitar. Dengan begitu materi terasa dekat dan tidak abstrak.',
      'Pengalaman belajarnya berupa proyek kecil yang menyerupai pekerjaan sebenarnya, lalu hasilnya dipresentasikan dan dibahas bersama. Saya juga mengundang masukan dari praktisi bila memungkinkan.',
      'Saya memulai dari pengalaman murid, lalu menghubungkannya dengan standar kerja yang berlaku. Di akhir mereka diminta menyebutkan di mana keterampilan ini akan dipakai.'],
    cek: ['Saya mengecek pemahaman lewat tanya jawab, pengamatan saat praktik, dan exit ticket di akhir. Umpan balik saya berikan langsung saat murid bekerja, lalu dirangkum di penutup.',
      'Selama kegiatan saya berkeliling membawa checklist unjuk kerja untuk mencatat capaian tiap murid. Jika ada kesalahan konsep, saya hentikan sebentar dan jelaskan ulang.',
      'Pengecekan dilakukan bertahap: pertanyaan pemantik di awal, kuis singkat di tengah, dan refleksi tertulis di akhir. Dari jawaban itu saya menyesuaikan penjelasan.',
      'Saya memberi umpan balik yang spesifik pada hasil kerja murid dan memberi kesempatan memperbaikinya. Murid juga saya ajak saling menilai dengan rubrik.'],
    tantangan: ['Tantangan utama adalah alokasi waktu yang terbatas dan kemampuan murid yang beragam. Saya mohon masukan Bapak/Ibu supervisor soal pengelolaan waktu dan diferensiasi tugas.',
      'Saya khawatir alat dan bahan tidak cukup untuk semua kelompok, jadi saya siapkan giliran kerja. Dukungan yang saya harapkan adalah masukan tentang cara menjaga semua murid tetap terlibat.',
      'Kemungkinan kendalanya jaringan internet dan perangkat digital yang terbatas; saya sudah menyiapkan materi cadangan. Saya butuh saran supervisor agar tetap efektif jika kendala itu muncul.',
      'Yang saya antisipasi adalah murid yang pasif saat kerja kelompok. Saya akan membagi peran dan berkeliling, dan saya terbuka untuk masukan strategi lain.',
      'Tantangannya menjaga keseimbangan antara penjelasan dan waktu praktik. Dukungan yang saya perlukan berupa masukan mengenai pengelolaan waktu dan penilaian unjuk kerja.'],
    berhasil: ['Menurut saya yang paling berhasil adalah {a}. Buktinya, {b}.',
      'Bagian yang paling saya rasakan berhasil: {a}. Hal itu terlihat dari {b}.',
      '{A} adalah bagian yang menurut saya paling berhasil membuat murid belajar mendalam; {b}.'],
    bukti: ['murid aktif bertanya dan menanggapi teman', 'sebagian besar murid dapat menyelesaikan tugas sesuai kriteria', 'murid mampu menjelaskan kembali hasil kerjanya dengan kata-kata sendiri', 'hasil kerja murid menunjukkan pemahaman yang meningkat dibanding pertemuan sebelumnya', 'murid terlihat antusias dan bertahan fokus sampai akhir kegiatan', 'banyak murid yang menyelesaikan tugas tepat waktu tanpa banyak bantuan'],
    kendalaA: ['Kendala utama yang saya rasakan adalah waktu yang terasa kurang untuk kegiatan praktik.', 'Beberapa alat dan bahan jumlahnya terbatas sehingga harus dipakai bergantian.', 'Kemampuan murid dalam satu kelas cukup beragam, jadi kecepatan kerjanya berbeda-beda.', 'Perangkat digital dan jaringan internet kadang kurang stabil.', 'Jadwal praktisi atau mitra sulit dicocokkan dengan jam pelajaran.', 'Secara umum tidak ada kendala besar, hanya waktu transisi yang agak panjang.', 'Jumlah murid yang cukup banyak membuat pendampingan individual tidak selalu sempat.'],
    kendalaB: ['Dukungan yang saya butuhkan: tambahan alat dan bahan serta jadwal praktik yang lebih longgar.', 'Saya berharap ada pendampingan dalam menyusun tugas bertingkat.', 'Saya butuh dukungan sekolah untuk membuka komunikasi dengan mitra industri.', 'Masukan teknis tentang pengelolaan kelas akan sangat membantu.', 'Bila memungkinkan, mohon dibantu pengadaan perangkat cadangan.', 'Saya terbuka untuk berdiskusi dengan supervisor tentang strategi mengatasinya.'],
    tantanganA: ['Tantangan utama adalah alokasi waktu yang terbatas dan kemampuan murid yang beragam.', 'Saya khawatir alat dan bahan tidak cukup untuk semua kelompok, jadi saya siapkan giliran kerja.', 'Kemungkinan kendalanya jaringan internet dan perangkat digital yang terbatas; materi cadangan sudah saya siapkan.', 'Yang saya antisipasi adalah murid yang pasif saat kerja kelompok.', 'Tantangannya menjaga keseimbangan antara penjelasan dan waktu praktik.', 'Saya mengantisipasi murid yang cepat selesai dan murid yang butuh waktu lebih lama.'],
    tantanganB: ['Saya mohon masukan Bapak/Ibu supervisor soal pengelolaan waktu dan diferensiasi tugas.', 'Dukungan yang saya harapkan adalah masukan tentang cara menjaga semua murid tetap terlibat.', 'Saya butuh saran supervisor agar kegiatan tetap efektif jika kendala itu muncul.', 'Saya akan membagi peran dan berkeliling, dan terbuka untuk strategi lain.', 'Dukungan yang saya perlukan berupa masukan mengenai penilaian unjuk kerja.', 'Saya berharap supervisor dapat memberi umpan balik pada bagian ini.'],
    lanjutTujuan: ['Indikator keberhasilannya sudah saya rumuskan agar mudah dicek di akhir pelajaran.', 'Di akhir kegiatan murid saya minta menjelaskan kembali apa yang mereka pahami.', 'Saya juga menyiapkan satu pertanyaan penguji pemahaman untuk dijawab murid.', 'Targetnya tidak hanya hasil, tetapi juga proses berpikir murid.'],
    lanjutKondisi: ['Hasil pemetaan itu saya pakai untuk menentukan siapa yang perlu pendampingan.', 'Saya juga memperhatikan kesiapan emosional murid di awal pelajaran.', 'Beberapa murid saya tempatkan sebagai tutor sebaya.', 'Pemetaannya saya perbarui setiap beberapa pertemuan.'],
    lanjutBermakna: ['Di akhir, murid saya minta menyebutkan di mana keterampilan itu akan dipakai.', 'Kasusnya saya ambil dari situasi yang dekat dengan jurusan mereka.', 'Saya berusaha agar hasil kerja murid bisa dipakai nyata, bukan sekadar latihan.', 'Mitra atau alumni saya libatkan bila memungkinkan.'],
    lanjutCek: ['Catatan capaian saya simpan untuk bahan remedial dan pengayaan.', 'Umpan balik saya sampaikan dengan menyebut bagian yang sudah benar lebih dulu.', 'Murid juga saya minta mengecek pekerjaannya dengan rubrik.', 'Hasil pengecekan saya pakai untuk menyesuaikan penjelasan pada pertemuan berikutnya.'],
    komitmen: ['Saya berkomitmen menindaklanjuti hasil supervisi ini, terutama {a}, dan akan melaporkan perkembangannya kepada supervisor.',
      'Saya akan memperbaiki {a} pada pembelajaran berikutnya, serta mempertahankan hal-hal yang sudah baik.',
      'Terima kasih atas masukannya. Saya berkomitmen untuk {ak} dan mengikuti pembinaan yang disepakati.',
      'Saya siap menjalankan tindak lanjut yang disepakati, khususnya terkait {a}, dan akan berdiskusi dengan rekan sejawat bila menemui kendala.'],
    kendala: ['Kendalanya terutama waktu yang terasa kurang, serta beberapa alat yang jumlahnya terbatas. Dukungan yang saya butuhkan: tambahan alat/bahan dan jadwal praktik yang lebih longgar.',
      'Kendala yang saya rasakan adalah kemampuan murid yang beragam dan perangkat digital yang terbatas. Saya berharap ada pendampingan dalam menyusun tugas bertingkat.',
      'Waktu dan sarana menjadi kendala utama; untuk kemitraan, jadwal praktisi sulit dicocokkan. Saya butuh dukungan sekolah untuk membuka komunikasi dengan mitra.',
      'Secara umum tidak ada kendala besar, hanya waktu transisi yang agak panjang. Dukungan yang saya harapkan berupa masukan teknis pengelolaan kelas.'],
    ubah: ['Jika mengulang, saya ingin memperbaiki {a}. Selain itu saya akan menambah waktu untuk refleksi di akhir.',
      'Saya akan mengubah {a}, lalu menyiapkan tugas yang lebih bervariasi. Pembagian waktu juga akan saya rapikan.',
      'Yang ingin saya ubah terutama {a}; kegiatan lain akan saya pertahankan karena sudah berjalan sesuai rencana.'],
    ubahKecil: ['Jika mengulang, saya akan menambah variasi kegiatan dan memberi lebih banyak waktu bagi murid untuk refleksi.', 'Secara umum sudah sesuai rencana; saya hanya ingin merapikan pembagian waktu dan memperbanyak umpan balik individual.', 'Saya akan mempertahankan alurnya dan sedikit memperkaya pertanyaan pemantik agar lebih menantang.']
  };

  return { SUP: SUP, TELAAH: TELAAH, TAMBAH: TAMBAH, P: P, GURU: GURU };
})();
